version: '3.1'
services:
    auth_service:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
        volumes: 
            - ./sql/:/docker-entrypoint-initdb.d/
    
        