version: '3.1'
services:
    auth_service:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
        volumes: 
            - ./sql/:/docker-entrypoint-initdb.d/
    nats:
        image: nats-streaming
        restart: always
        ports:
            - 4222:4222
            - 6222:6222
            - 8222:8222