version: '3.1'
services:
    auth_service:
        image: postgres
        restart: always
        ports:
            - 5431:5432
        environment:
            POSTGRES_PASSWORD: password
        volumes: 
            - ./auth/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    tweet_service:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
        volumes: 
            - ./tweet/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        