version: '3.1'
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
        volumes: 
            - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        