// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: action_message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Action int32

const (
	Action_UNKNOWNE_ACTION Action = 0
	Action_CREATED         Action = 1
	Action_UPDATED         Action = 2
	Action_DELETED         Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "UNKNOWNE_ACTION",
		1: "CREATED",
		2: "UPDATED",
		3: "DELETED",
	}
	Action_value = map[string]int32{
		"UNKNOWNE_ACTION": 0,
		"CREATED":         1,
		"UPDATED":         2,
		"DELETED":         3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_action_message_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_action_message_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_action_message_proto_rawDescGZIP(), []int{0}
}

var File_action_message_proto protoreflect.FileDescriptor

var file_action_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x2a, 0x44, 0x0a, 0x06, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x45,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45,
	0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_action_message_proto_rawDescOnce sync.Once
	file_action_message_proto_rawDescData = file_action_message_proto_rawDesc
)

func file_action_message_proto_rawDescGZIP() []byte {
	file_action_message_proto_rawDescOnce.Do(func() {
		file_action_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_action_message_proto_rawDescData)
	})
	return file_action_message_proto_rawDescData
}

var file_action_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_action_message_proto_goTypes = []interface{}{
	(Action)(0), // 0: v1.Action
}
var file_action_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_action_message_proto_init() }
func file_action_message_proto_init() {
	if File_action_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_action_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_message_proto_goTypes,
		DependencyIndexes: file_action_message_proto_depIdxs,
		EnumInfos:         file_action_message_proto_enumTypes,
	}.Build()
	File_action_message_proto = out.File
	file_action_message_proto_rawDesc = nil
	file_action_message_proto_goTypes = nil
	file_action_message_proto_depIdxs = nil
}
