// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: notification_message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Notification_Type int32

const (
	Notification_UNKNOWNE Notification_Type = 0
	Notification_TWEET    Notification_Type = 1
	Notification_FOLLOW   Notification_Type = 2
)

// Enum value maps for Notification_Type.
var (
	Notification_Type_name = map[int32]string{
		0: "UNKNOWNE",
		1: "TWEET",
		2: "FOLLOW",
	}
	Notification_Type_value = map[string]int32{
		"UNKNOWNE": 0,
		"TWEET":    1,
		"FOLLOW":   2,
	}
)

func (x Notification_Type) Enum() *Notification_Type {
	p := new(Notification_Type)
	*p = x
	return p
}

func (x Notification_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Notification_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_message_proto_enumTypes[0].Descriptor()
}

func (Notification_Type) Type() protoreflect.EnumType {
	return &file_notification_message_proto_enumTypes[0]
}

func (x Notification_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Notification_Type.Descriptor instead.
func (Notification_Type) EnumDescriptor() ([]byte, []int) {
	return file_notification_message_proto_rawDescGZIP(), []int{0, 0}
}

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*Notification_Tweet
	//	*Notification_Follow
	Data        isNotification_Data `protobuf_oneof:"Data"`
	Id          int64               `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	UserId      int64               `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type        Notification_Type   `protobuf:"varint,5,opt,name=type,proto3,enum=v1.Notification_Type" json:"type,omitempty"`
	Title       string              `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description string              `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Opened      bool                `protobuf:"varint,8,opt,name=opened,proto3" json:"opened,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_message_proto_rawDescGZIP(), []int{0}
}

func (m *Notification) GetData() isNotification_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Notification) GetTweet() *Tweet {
	if x, ok := x.GetData().(*Notification_Tweet); ok {
		return x.Tweet
	}
	return nil
}

func (x *Notification) GetFollow() *Follow {
	if x, ok := x.GetData().(*Notification_Follow); ok {
		return x.Follow
	}
	return nil
}

func (x *Notification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notification) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Notification) GetType() Notification_Type {
	if x != nil {
		return x.Type
	}
	return Notification_UNKNOWNE
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Notification) GetOpened() bool {
	if x != nil {
		return x.Opened
	}
	return false
}

type isNotification_Data interface {
	isNotification_Data()
}

type Notification_Tweet struct {
	Tweet *Tweet `protobuf:"bytes,1,opt,name=tweet,proto3,oneof"`
}

type Notification_Follow struct {
	Follow *Follow `protobuf:"bytes,2,opt,name=follow,proto3,oneof"`
}

func (*Notification_Tweet) isNotification_Data() {}

func (*Notification_Follow) isNotification_Data() {}

var File_notification_message_proto protoreflect.FileDescriptor

var file_notification_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31,
	0x1a, 0x13, 0x74, 0x77, 0x65, 0x65, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x02, 0x0a, 0x0c,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x05,
	0x74, 0x77, 0x65, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x48, 0x00, 0x52, 0x05, 0x74, 0x77, 0x65, 0x65, 0x74, 0x12,
	0x24, 0x0a, 0x06, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x48, 0x00, 0x52, 0x06, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x29,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x76,
	0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x22, 0x2b, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x54, 0x57, 0x45, 0x45, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x4f,
	0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x02, 0x42, 0x06, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notification_message_proto_rawDescOnce sync.Once
	file_notification_message_proto_rawDescData = file_notification_message_proto_rawDesc
)

func file_notification_message_proto_rawDescGZIP() []byte {
	file_notification_message_proto_rawDescOnce.Do(func() {
		file_notification_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_notification_message_proto_rawDescData)
	})
	return file_notification_message_proto_rawDescData
}

var file_notification_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notification_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_notification_message_proto_goTypes = []interface{}{
	(Notification_Type)(0), // 0: v1.Notification.Type
	(*Notification)(nil),   // 1: v1.Notification
	(*Tweet)(nil),          // 2: v1.Tweet
	(*Follow)(nil),         // 3: v1.Follow
}
var file_notification_message_proto_depIdxs = []int32{
	2, // 0: v1.Notification.tweet:type_name -> v1.Tweet
	3, // 1: v1.Notification.follow:type_name -> v1.Follow
	0, // 2: v1.Notification.type:type_name -> v1.Notification.Type
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_notification_message_proto_init() }
func file_notification_message_proto_init() {
	if File_notification_message_proto != nil {
		return
	}
	file_tweet_message_proto_init()
	file_follow_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_notification_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_notification_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Notification_Tweet)(nil),
		(*Notification_Follow)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notification_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_message_proto_goTypes,
		DependencyIndexes: file_notification_message_proto_depIdxs,
		EnumInfos:         file_notification_message_proto_enumTypes,
		MessageInfos:      file_notification_message_proto_msgTypes,
	}.Build()
	File_notification_message_proto = out.File
	file_notification_message_proto_rawDesc = nil
	file_notification_message_proto_goTypes = nil
	file_notification_message_proto_depIdxs = nil
}
