// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: type_message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Type int32

const (
	Type_UNKNOWNE_TYPE Type = 0
	Type_TWEET         Type = 1
	Type_FOLLOW        Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "UNKNOWNE_TYPE",
		1: "TWEET",
		2: "FOLLOW",
	}
	Type_value = map[string]int32{
		"UNKNOWNE_TYPE": 0,
		"TWEET":         1,
		"FOLLOW":        2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_type_message_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_type_message_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_type_message_proto_rawDescGZIP(), []int{0}
}

var File_type_message_proto protoreflect.FileDescriptor

var file_type_message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x2a, 0x30, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x57, 0x45, 0x45, 0x54, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_type_message_proto_rawDescOnce sync.Once
	file_type_message_proto_rawDescData = file_type_message_proto_rawDesc
)

func file_type_message_proto_rawDescGZIP() []byte {
	file_type_message_proto_rawDescOnce.Do(func() {
		file_type_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_type_message_proto_rawDescData)
	})
	return file_type_message_proto_rawDescData
}

var file_type_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_type_message_proto_goTypes = []interface{}{
	(Type)(0), // 0: v1.Type
}
var file_type_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_type_message_proto_init() }
func file_type_message_proto_init() {
	if File_type_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_type_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_type_message_proto_goTypes,
		DependencyIndexes: file_type_message_proto_depIdxs,
		EnumInfos:         file_type_message_proto_enumTypes,
	}.Build()
	File_type_message_proto = out.File
	file_type_message_proto_rawDesc = nil
	file_type_message_proto_goTypes = nil
	file_type_message_proto_depIdxs = nil
}
